### ISSUE TITLE
What's the rationale for salv.el?

### ISSUE THREAD

**Issue by randomwangran** [alphapapa/salv.el#1]
If a buffer is modified and not saved, it is a strong signal for the user.

Was a modification the desired change? If so, save it.

If not, undo the modification. This is very helpful for data protection.

Please let me know your thoughts.

Ran

**Comment by alphapapa** [comment]
I use `real-auto-save-mode` (or, now, this) for my Org files in `~/org`.  I think of them as notebooks: once I type something into one, I don't want to have to remember to save the file for the data to be saved.  I also sync those files to other systems, so I don't want to have to deal with `recover-this-file` and conflicts.

**Comment by randomwangran** [comment]
I confess that Emacs has trained me to use =C-x C-s= as second nature. It's now a real challenge to go back.

`salv.el` is a powerful tool for automation from my perspective.

The line here:

https://github.com/alphapapa/salv.el/blob/aa32b6b10e60c10f329a29ff29fa2a6e447836a1/salv.el#L94

It does what the author's intention.

I was wondering if we could customize this part?

For example, a use case can be extended to the blogger `systemcrafters` work.

https://systemcrafters.net/build-a-second-brain-in-emacs/5-org-roam-hacks/#automatically-copy-or-move-completed-tasks-to-dailies

By calling =my/org-roam-copy-todo-to-today= with `salv.el`:

```elisp
 (setf salv-idle-timer (run-with-idle-timer
                         salv-idle-seconds nil #'my/org-roam-copy-todo-to-today)))
```

I am not sure this is a good direction instead of depending on `crontab` or a similar tool outside Emacs.
